const { chromium } = require('playwright');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}}); await p.addInitScript(()=>{try{localStorage.setItem('wesserWelcomeSeen','1')}catch(e){}});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file:///'+require('path').resolve(__dirname, '..', 'index.html').split(String.fromCharCode(92)).join('/'));
await p.evaluate(()=>{openReset(); openCheckinHistorial();});
let t=await p.locator('#resetBody').innerText();
ok(t.includes('Aún no has completado ninguna sesión de Reset.') && t.includes('Aún no has hecho ningún check-in.'), 'estados vacíos con su texto');
await p.locator('#resetBody button:has-text("Hacer un check-in")').click();
ok(await p.evaluate(()=>resetStep)==='checkin', 'vacío → «Hacer un check-in» abre el check-in');
await p.evaluate(()=>{openCheckinHistorial();});
await p.locator('#resetBody button:has-text("Empezar un Reset")').click();
ok(await p.evaluate(()=>resetStep)===1, 'vacío → «Empezar un Reset» va a R · Reconoce');
await p.evaluate(()=>{ for(let k=0;k<7;k++){ startCheckin(); checkinState[0][0]=true; checkinState[2][1]=true; saveCheckin(); } state.resetHistory.unshift(newRecord({senal:'x',examResultado:'poco flujo',examRendimiento:'paro menos',micro:'Simplificar la apertura',stops:10,pacto:'p'})); save(); openCheckinHistorial(); });
t=await p.locator('#resetBody').innerText();
const tc=await p.locator('#resetBody').evaluate(e=>e.textContent); ok(tc.includes('El contexto: poco flujo') && tc.includes('Mi forma de trabajar: paro menos') || false && t.includes('Mi forma de trabajar: paro menos'), 'etiquetas del Reset alineadas con Examina');
ok(await p.locator('#resetBody .history-item').count()===5 && t.includes('Mostrar más'), 'check-ins limitados a 5 con «Mostrar más»');
const li = await p.locator('#resetBody .history-item li').first().innerText();
ok(li==='Anticipo el rechazo', 'solo el título de cada señal: '+li);
await p.locator('#resetBody [data-action="borrarCheckin"]').first().click();
ok(await p.locator('#confirmTitle').innerText()==='¿Eliminar este check-in?', 'eliminar check-in pide confirmación');
await p.locator('#confirmOk').click();
ok(await p.evaluate(()=>state.checkins.length)===6, 'check-in eliminado');
await p.locator('#resetBody button:has-text("Mostrar más")').click();
ok(await p.locator('#resetBody .history-item').count()===6, '«Mostrar más» enseña el resto');
await p.locator('#resetBody').screenshot({path:require('path').join(__dirname, 'out')+'/hist.png'});
ok(errs.length===0,'sin errores de JS '+errs.join('|'));
await b.close();})();
