const { chromium } = require('playwright');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
(async()=>{const b=await chromium.launch();const p=await b.newPage(); await p.addInitScript(()=>{try{localStorage.setItem('wesserWelcomeSeen','1')}catch(e){}});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file:///'+require('path').resolve(__dirname, '..', 'index.html').split(String.fromCharCode(92)).join('/'));
const top=()=>p.evaluate(()=>Overlays.top());
await p.evaluate(()=>{state.kitHerramienta='Suspiro fisiológico'; activarKitPlan();});
ok(await p.locator('#toolTitle').innerText()==='Suspiro Fisiológico', 'herramienta interna: se abre directamente');
await p.evaluate(()=>{closeTool(); state.kitHerramienta='grounding 5-4-3-2-1'; activarKitPlan();});
ok(await p.locator('#toolTitle').innerText().then(t=>t.startsWith('Grounding')), 'nombre de herramienta con otras mayúsculas: también se abre');
await p.evaluate(()=>{closeTool(); state.kitHerramienta='Salir a respirar al parque'; state.kitPersona='Laura'; state.kitPedira='que me observe dos paradas'; activarKitPlan();});
const t=await p.locator('#modalSheet').innerText();
ok(await top()==='modal' && t.includes('Este es tu recurso personal') && t.includes('«Salir a respirar al parque»'), 'recurso personal: se muestra lo guardado, no abre el Suspiro');
ok(t.includes('Si sigo atascado, pido apoyo a Laura: «que me observe dos paradas»'), 'incluye el apoyo con sentido');
await p.locator('[data-action="kitSuggestedTool"]').click();
ok(await p.locator('#toolTitle').innerText()==='Suspiro Fisiológico' && await top()==='tool', 'la herramienta parecida solo se abre si la eliges');
await p.evaluate(()=>{closeTool(); state.kitHerramienta='Llamar a mi madre'; activarKitPlan();});
ok(await p.locator('[data-action="kitSuggestedTool"]').count()===0, 'sin parecido, no se sugiere ninguna herramienta');
await p.evaluate(()=>{closeModal(); state.kitSenales=[]; openReset(); openKit();});
ok((await p.locator('#resetBody').innerText()).includes('Elige hasta 3: así tu plan es fácil de recordar'), 'límite explicado de antemano como decisión de diseño');
ok((await p.locator('#resetBody .kit-flow').innerText()).includes('Pido apoyo a Laura: «que me observe dos paradas»'), 'caja SI SIGO ATASCADO: «Pido apoyo a…»');
for(let i=0;i<4;i++) await p.locator('#kitSenalChips button').nth(i).click();
ok((await p.locator('#kitSenalChips + .field-error').innerText()).includes('Para que tu plan sea fácil de recordar, puedes elegir hasta 3 señales'), 'aviso del límite reformulado');
ok(errs.length===0,'sin errores de JS '+errs.join('|'));
await b.close();})();
