const { chromium } = require('playwright');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
(async()=>{const b=await chromium.launch();const p=await b.newPage(); await p.addInitScript(()=>{try{localStorage.setItem('wesserWelcomeSeen','1')}catch(e){}});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file:///'+require('path').resolve(__dirname, '..', 'index.html').split(String.fromCharCode(92)).join('/'));
await p.evaluate(()=>{startNoSeQueNecesito(); setNsqnAnswer('acelerado',true);});
let t=await p.locator('#toolBody').innerText();
ok(t.includes('Empieza por este paso sugerido:') && t.includes('Suspiro fisiológico') && !t.includes('urgente'), 'una respuesta: «Empieza por este paso sugerido»');
await p.evaluate(()=>{setNsqnAnswer('dias',true);});
t=await p.locator('#toolBody').innerText();
ok(t.includes('Empieza por este paso sugerido:') && t.indexOf('Modo Reset') < t.indexOf('Suspiro') && t.includes('Otras opciones'), 'varias: Reset primero y el resto como otras opciones');
await p.evaluate(()=>{startNoSeQueNecesito(); ['acelerado','cabeza','evitando','dias'].forEach(k=>setNsqnAnswer(k,false));});
t=await p.locator('#toolBody').innerText();
ok(t.includes('Con estas respuestas no tengo una herramienta clara para recomendarte. Puedes hacer un Checkpoint o elegir una herramienta manualmente.'), 'sin recomendación: texto nuevo');
await p.locator('#toolBody button:has-text("Ver herramientas")').click();
ok(await p.evaluate(()=>Overlays.top()===null && document.getElementById('view-herramientas').classList.contains('active')), '«Ver herramientas» lleva a la Caja de Herramientas');
await p.evaluate(()=>{startNoSeQueNecesito(); ['acelerado','cabeza','evitando','dias'].forEach(k=>setNsqnAnswer(k,false));});
await p.locator('#toolBody button:has-text("Hacer un Checkpoint")').click();
ok(await p.locator('#toolTitle').innerText()==='Checkpoint de mitad de turno', '«Hacer un Checkpoint» abre el Checkpoint');
ok(errs.length===0,'sin errores de JS '+errs.join('|'));
await b.close();})();
