const { chromium } = require('playwright');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}}); await p.addInitScript(()=>{try{localStorage.setItem('wesserWelcomeSeen','1')}catch(e){}});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file:///'+require('path').resolve(__dirname, '..', 'index.html').split(String.fromCharCode(92)).join('/'));
const n=()=>p.evaluate(()=>resetStops);
await p.evaluate(()=>{localStorage.clear(); openReset(); resetMicro='Simplificar la apertura'; resetStops=0; resetGoto(5);});
await p.locator('#incrementStop3Btn').click();
ok(await n()===3, '+3 suma 3');
await p.locator('#incrementStopBtn').click();
ok(await n()===4, '+1 suma 1 (4)');
await p.locator('#decrementStopBtn').click();
ok(await n()===3, 'deshacer revierte el último +1 (3)');
await p.locator('#decrementStopBtn').click();
ok(await n()===0, 'deshacer revierte el +3 completo (0)');
await p.evaluate(()=>{resetStops=8; resetStopsUndo=[]; renderResetStep();});
ok(await p.locator('#incrementStop3Btn').count()===0, 'con 8 paradas ya no se ofrece +3');
await p.locator('#incrementStopBtn').click(); await p.locator('#incrementStopBtn').click(); await p.locator('#incrementStopBtn').click();
ok(await n()===10, '+1 nunca pasa de 10');
ok(await p.locator('#allStopsBtn').count()===0, 'con 10 desaparece «Ya he hecho las 10»');
await p.evaluate(()=>{resetStops=2; resetStopsUndo=[]; renderResetStep();});
await p.locator('#allStopsBtn').click();
ok(await p.locator('#confirmTitle').innerText()==='¿Has hecho ya las 10 paradas?' && await p.evaluate(()=>document.activeElement.id)==='confirmCancel', '«Ya he hecho las 10» pide confirmación (foco en Seguir contando)');
await p.keyboard.press('Escape');
ok(await n()===2 && await p.evaluate(()=>resetStep)===5, 'cancelar no cambia nada');
await p.locator('#allStopsBtn').click(); await p.locator('#confirmOk').click();
ok(await p.evaluate(()=>resetStep===6 && resetStops===10 && JSON.parse(localStorage.getItem('wesserAppState')).resetProgress.stops===10), 'confirmar marca 10 y pasa a «¿Qué he aprendido?»');
await p.locator('#resetBody').screenshot({path:require('path').join(__dirname, 'out')+'/stops-row.png'}).catch(()=>{});
await p.evaluate(()=>{resetStops=4; resetGoto(5);});
await p.locator('#resetBody .btn-row').first().screenshot({path:require('path').join(__dirname, 'out')+'/stops-row.png'});
ok(errs.length===0,'sin errores de JS '+errs.join('|'));
await b.close();})();
