const { chromium } = require('playwright');
const path = require('path'), fs = require('fs');
const URL = 'file:///' + path.resolve(__dirname, '..', 'index.html').split(String.fromCharCode(92)).join('/');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
require('fs').mkdirSync(require('path').join(__dirname, 'out'), { recursive: true });
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 390, height: 844 } });
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  const top = () => p.evaluate(() => Overlays.top());
  await p.goto(URL); await p.evaluate(() => localStorage.clear()); await p.reload();
  ok(await top() === 'modal' && (await p.locator('#modalSheet h2').innerText()).includes('Bienvenido'), 'primera vez sin datos: aparece la bienvenida');
  ok(await p.evaluate(() => document.getElementById('modalSheet').getAttribute('aria-labelledby') === 'modalTitle'), 'diálogo con nombre accesible');
  await p.locator('[data-action="welcomeNext"]').click();
  ok((await p.locator('#modalSheet h2').innerText()).includes('Cuándo usar'), 'paso 2');
  ok(await p.evaluate(() => document.activeElement.dataset.action) === 'welcomeNext', 'el foco sigue en «Siguiente» al cambiar de paso');
  await p.keyboard.press('Enter');
  ok((await p.locator('#modalSheet h2').innerText()).includes('Prepara tu Kit'), 'paso 3 (con teclado)');
  await p.screenshot({ path: path.join(__dirname, 'out', 'welcome3.png') });
  await p.locator('[data-action="welcomeKit"]').click();
  ok(await p.evaluate(() => Overlays.top() === 'reset' && resetStep === 'kit'), '«Preparar mi Kit» abre el Kit');
  await p.evaluate(() => closeReset()); await p.reload();
  ok(await top() === null, 'no vuelve a aparecer al recargar');
  await p.evaluate(() => { localStorage.clear(); localStorage.setItem('wesserAppState', JSON.stringify({ dataVersion: 3, sepaEntries: [{ id: 1, createdAt: new Date().toISOString(), situacion: 'x', emociones: ['ira'], pensD: 'a', pensC: 'b', accion: 'c' }] })); });
  await p.reload();
  ok(await top() === null, 'quien ya tiene datos no la ve');
  await p.evaluate(() => openHelp());
  await p.locator('#helpOverlay button:has-text("Ver la bienvenida")').click();
  ok(await top() === 'modal', 'se puede volver a ver desde la Ayuda');
  await p.keyboard.press('Escape');
  ok(await top() === null, 'Escape la cierra');
  await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.locator('[data-action="welcomeClose"]').click();
  ok(await top() === null, '«Saltar» la cierra');
  // «Más tarde» (último paso) lleva a Aprender, aunque se abra desde otra sección
  await p.evaluate(() => { goto('diario'); showWelcome(2); });
  const kitPrincipal = await p.evaluate(() => document.querySelector('#modalSheet [data-action="welcomeKit"]').classList.contains('btn-navy') && document.querySelector('#modalSheet [data-action="welcomeClose"]').classList.contains('btn-outline'));
  await p.locator('#modalSheet button:text-is("Más tarde")').click();
  ok(kitPrincipal && await top() === null && await p.evaluate(() => document.querySelector('.view.active').id) === 'view-aprender', '«Preparar mi Kit» es la acción principal; «Más tarde» cierra la bienvenida y lleva a Aprender');
  ok(errs.length === 0, 'sin errores de JS ' + errs.join('|'));
  await b.close();
})();
